import Cimage1 from "./Assets/Home/C-img-1.png";
import Cimage2 from "./Assets/Home/C-img-2.png";
import Cimage3 from "./Assets/Home/C-img-3.png";
import Cimage4 from "./Assets/Home/C-img-4.png";
import Cimage5 from "./Assets/Home/C-img-5.png";
import Cimage6 from "./Assets/Home/C-img-6.png";
export const ProfileDetails = [
  {
    id: 1,
    Age: "25",
    Height: "5'7\"",
    Language: "English",
    Religion: "Hindu",
    caste: "Brahmin",
    City: "Chennai",
    State: "Tamil Nadu",
    country: "India",
    occupation: "Engineer",
    Address: "123 Street, Chennai, Tamil Nadu, India",
  },
  {
    id: 2,
    Age: "30",
    Height: "5'9\"",
    Language: "Tamil",
    Religion: "Christian",
    caste: "Nadar",
    City: "Coimbatore",
    State: "Tamil Nadu",
    country: "India",
    occupation: "Doctor",
    Address: "456 Avenue, Coimbatore, Tamil Nadu, India",
  },
  {
    id: 3,
    Age: "22",
    Height: "5'6\"",
    Language: "Hindi",
    Religion: "Muslim",
    caste: "Syed",
    City: "Mumbai",
    State: "Maharashtra",
    country: "India",
    occupation: "Teacher",
    Address: "789 Boulevard, Mumbai, Maharashtra, India",
  },
  {
    id: 4,
    Age: "29",
    Height: "5'8\"",
    Language: "Telugu",
    Religion: "Hindu",
    caste: "Kamma",
    City: "Hyderabad",
    State: "Telangana",
    country: "India",
    occupation: "Scientist",
    Address: "101 Circle, Hyderabad, Telangana, India",
  },
  {
    id: 5,
    Age: "27",
    Height: "5'7\"",
    Language: "Kannada",
    Religion: "Christian",
    caste: "Gowda",
    City: "Bangalore",
    State: "Karnataka",
    country: "India",
    occupation: "Lawyer",
    Address: "202 Drive, Bangalore, Karnataka, India",
  },
  {
    id: 6,
    Age: "26",
    Height: "5'9\"",
    Language: "Malayalam",
    Religion: "Hindu",
    caste: "Nair",
    City: "Kochi",
    State: "Kerala",
    country: "India",
    occupation: "Engineer",
    Address: "303 Lane, Kochi, Kerala, India",
  },
  {
    id: 7,
    Age: "24",
    Height: "5'8\"",
    Language: "Gujarati",
    Religion: "Jain",
    caste: "Bania",
    City: "Ahmedabad",
    State: "Gujarat",
    country: "India",
    occupation: "Doctor",
    Address: "404 Street, Ahmedabad, Gujarat, India",
  },
  {
    id: 8,
    Age: "31",
    Height: "5'10\"",
    Language: "Punjabi",
    Religion: "Sikh",
    caste: "Jat",
    City: "Amritsar",
    State: "Punjab",
    country: "India",
    occupation: "Teacher",
    Address: "505 Avenue, Amritsar, Punjab, India",
  },
  {
    id: 9,
    Age: "28",
    Height: "5'6\"",
    Language: "Marathi",
    Religion: "Hindu",
    caste: "Maratha",
    City: "Pune",
    State: "Maharashtra",
    country: "India",
    occupation: "Scientist",
    Address: "606 Circle, Pune, Maharashtra, India",
  },
  {
    id: 10,
    Age: "27",
    Height: "5'7\"",
    Language: "Bengali",
    Religion: "Hindu",
    caste: "Kayastha",
    City: "Kolkata",
    State: "West Bengal",
    country: "India",
    occupation: "Lawyer",
    Address: "707 Drive, Kolkata, West Bengal, India",
  },
  {
    id: 11,
    Age: "32",
    Height: "5'11\"",
    Language: "English",
    Religion: "Christian",
    caste: "Roman Catholic",
    City: "Goa",
    State: "Goa",
    country: "India",
    occupation: "Engineer",
    Address: "808 Lane, Goa, Goa, India",
  },
  {
    id: 12,
    Age: "25",
    Height: "5'9\"",
    Language: "Hindi",
    Religion: "Muslim",
    caste: "Pathan",
    City: "Lucknow",
    State: "Uttar Pradesh",
    country: "India",
    occupation: "Teacher",
    Address: "909 Street, Lucknow, Uttar Pradesh, India",
  },
  {
    id: 13,
    Age: "30",
    Height: "5'10\"",
    Language: "Tamil",
    Religion: "Hindu",
    caste: "Brahmin",
    City: "Madurai",
    State: "Tamil Nadu",
    country: "India",
    occupation: "Doctor",
    Address: "1010 Avenue, Madurai, Tamil Nadu, India",
  },
  {
    id: 14,
    Age: "28",
    Height: "5'8\"",
    Language: "Telugu",
    Religion: "Hindu",
    caste: "Reddy",
    City: "Vijayawada",
    State: "Andhra Pradesh",
    country: "India",
    occupation: "Scientist",
    Address: "1111 Circle, Vijayawada, Andhra Pradesh, India",
  },
  {
    id: 15,
    Age: "27",
    Height: "5'7\"",
    Language: "Kannada",
    Religion: "Christian",
    caste: "Gowda",
    City: "Mysore",
    State: "Karnataka",
    country: "India",
    occupation: "Lawyer",
    Address: "1212 Drive, Mysore, Karnataka, India",
  },
  {
    id: 16,
    Age: "26",
    Height: "5'6\"",
    Language: "Malayalam",
    Religion: "Hindu",
    caste: "Nair",
    City: "Trivandrum",
    State: "Kerala",
    country: "India",
    occupation: "Engineer",
    Address: "1313 Lane, Trivandrum, Kerala, India",
  },
  {
    id: 17,
    Age: "24",
    Height: "5'9\"",
    Language: "Gujarati",
    Religion: "Jain",
    caste: "Bania",
    City: "Surat",
    State: "Gujarat",
    country: "India",
    occupation: "Doctor",
    Address: "1414 Street, Surat, Gujarat, India",
  },
  {
    id: 18,
    Age: "29",
    Height: "5'10\"",
    Language: "Punjabi",
    Religion: "Sikh",
    caste: "Jat",
    City: "Ludhiana",
    State: "Punjab",
    country: "India",
    occupation: "Teacher",
    Address: "1515 Avenue, Ludhiana, Punjab, India",
  },
  {
    id: 19,
    Age: "28",
    Height: "5'7\"",
    Language: "Marathi",
    Religion: "Hindu",
    caste: "Maratha",
    City: "Nagpur",
    State: "Maharashtra",
    country: "India",
    occupation: "Scientist",
    Address: "1616 Circle, Nagpur, Maharashtra, India",
  },
  {
    id: 20,
    Age: "26",
    Height: "5'6\"",
    Language: "Bengali",
    Religion: "Hindu",
    caste: "Kayastha",
    City: "Durgapur",
    State: "West Bengal",
    country: "India",
    occupation: "Lawyer",
    Address: "1717 Drive, Durgapur, West Bengal, India",
  },
  {
    id: 21,
    Age: "32",
    Height: "5'11\"",
    Language: "English",
    Religion: "Christian",
    caste: "Roman Catholic",
    City: "Panaji",
    State: "Goa",
    country: "India",
    occupation: "Engineer",
    Address: "1818 Lane, Panaji, Goa, India",
  },
  {
    id: 22,
    Age: "25",
    Height: "5'7\"",
    Language: "Hindi",
    Religion: "Muslim",
    caste: "Syed",
    City: "Varanasi",
    State: "Uttar Pradesh",
    country: "India",
    occupation: "Teacher",
    Address: "1919 Street, Varanasi, Uttar Pradesh, India",
  },
  {
    id: 23,
    Age: "30",
    Height: "5'9\"",
    Language: "Tamil",
    Religion: "Hindu",
    caste: "Brahmin",
    City: "Salem",
    State: "Tamil Nadu",
    country: "India",
    occupation: "Doctor",
    Address: "2020 Avenue, Salem, Tamil Nadu, India",
  },
  {
    id: 24,
    Age: "28",
    Height: "5'8\"",
    Language: "Telugu",
    Religion: "Hindu",
    caste: "Kamma",
    City: "Guntur",
    State: "Andhra Pradesh",
    country: "India",
    occupation: "Scientist",
    Address: "2121 Circle, Guntur, Andhra Pradesh, India",
  },
  {
    id: 25,
    Age: "27",
    Height: "5'7\"",
    Language: "Kannada",
    Religion: "Christian",
    caste: "Gowda",
    City: "Hubli",
    State: "Karnataka",
    country: "India",
    occupation: "Lawyer",
    Address: "2222 Drive, Hubli, Karnataka, India",
  },
  {
    id: 26,
    Age: "26",
    Height: "5'6\"",
    Language: "Malayalam",
    Religion: "Hindu",
    caste: "Nair",
    City: "Kozhikode",
    State: "Kerala",
    country: "India",
    occupation: "Engineer",
    Address: "2323 Lane, Kozhikode, Kerala, India",
  },
  {
    id: 27,
    Age: "24",
    Height: "5'9\"",
    Language: "Gujarati",
    Religion: "Jain",
    caste: "Bania",
    City: "Rajkot",
    State: "Gujarat",
    country: "India",
    occupation: "Doctor",
    Address: "2424 Street, Rajkot, Gujarat, India",
  },
  {
    id: 28,
    Age: "29",
    Height: "5'10\"",
    Language: "Punjabi",
    Religion: "Sikh",
    caste: "Jat",
    City: "Patiala",
    State: "Punjab",
    country: "India",
    occupation: "Teacher",
    Address: "2525 Avenue, Patiala, Punjab, India",
  },
  {
    id: 29,
    Age: "28",
    Height: "5'7\"",
    Language: "Marathi",
    Religion: "Hindu",
    caste: "Maratha",
    City: "Aurangabad",
    State: "Maharashtra",
    country: "India",
    occupation: "Scientist",
    Address: "2626 Circle, Aurangabad, Maharashtra, India",
  },
  {
    id: 30,
    Age: "26",
    Height: "5'6\"",
    Language: "Bengali",
    Religion: "Hindu",
    caste: "Kayastha",
    City: "Asansol",
    State: "West Bengal",
    country: "India",
    occupation: "Lawyer",
    Address: "2727 Drive, Asansol, West Bengal, India",
  },
  {
    id: 31,
    Age: "32",
    Height: "5'11\"",
    Language: "English",
    Religion: "Christian",
    caste: "Roman Catholic",
    City: "Margao",
    State: "Goa",
    country: "India",
    occupation: "Engineer",
    Address: "2828 Lane, Margao, Goa, India",
  },
  {
    id: 32,
    Age: "25",
    Height: "5'7\"",
    Language: "Hindi",
    Religion: "Muslim",
    caste: "Pathan",
    City: "Agra",
    State: "Uttar Pradesh",
    country: "India",
    occupation: "Teacher",
    Address: "2929 Street, Agra, Uttar Pradesh, India",
  },
  {
    id: 33,
    Age: "30",
    Height: "5'9\"",
    Language: "Tamil",
    Religion: "Hindu",
    caste: "Brahmin",
    City: "Thanjavur",
    State: "Tamil Nadu",
    country: "India",
    occupation: "Doctor",
    Address: "3030 Avenue, Thanjavur, Tamil Nadu, India",
  },
  {
    id: 34,
    Age: "28",
    Height: "5'8\"",
    Language: "Telugu",
    Religion: "Hindu",
    caste: "Reddy",
    City: "Tirupati",
    State: "Andhra Pradesh",
    country: "India",
    occupation: "Scientist",
    Address: "3131 Circle, Tirupati, Andhra Pradesh, India",
  },
  {
    id: 35,
    Age: "27",
    Height: "5'7\"",
    Language: "Kannada",
    Religion: "Christian",
    caste: "Gowda",
    City: "Mangalore",
    State: "Karnataka",
    country: "India",
    occupation: "Lawyer",
    Address: "3232 Drive, Mangalore, Karnataka, India",
  },
  {
    id: 36,
    Age: "26",
    Height: "5'6\"",
    Language: "Malayalam",
    Religion: "Hindu",
    caste: "Nair",
    City: "Kollam",
    State: "Kerala",
    country: "India",
    occupation: "Engineer",
    Address: "3333 Lane, Kollam, Kerala, India",
  },
  {
    id: 37,
    Age: "24",
    Height: "5'9\"",
    Language: "Gujarati",
    Religion: "Jain",
    caste: "Bania",
    City: "Vadodara",
    State: "Gujarat",
    country: "India",
    occupation: "Doctor",
    Address: "3434 Street, Vadodara, Gujarat, India",
  },
  {
    id: 38,
    Age: "29",
    Height: "5'10\"",
    Language: "Punjabi",
    Religion: "Sikh",
    caste: "Jat",
    City: "Bathinda",
    State: "Punjab",
    country: "India",
    occupation: "Teacher",
    Address: "3535 Avenue, Bathinda, Punjab, India",
  },
  {
    id: 39,
    Age: "28",
    Height: "5'7\"",
    Language: "Marathi",
    Religion: "Hindu",
    caste: "Maratha",
    City: "Solapur",
    State: "Maharashtra",
    country: "India",
    occupation: "Scientist",
    Address: "3636 Circle, Solapur, Maharashtra, India",
  },
  {
    id: 40,
    Age: "26",
    Height: "5'6\"",
    Language: "Bengali",
    Religion: "Hindu",
    caste: "Kayastha",
    City: "Siliguri",
    State: "West Bengal",
    country: "India",
    occupation: "Lawyer",
    Address: "3737 Drive, Siliguri, West Bengal, India",
  },
  {
    id: 41,
    Age: "32",
    Height: "5'11\"",
    Language: "English",
    Religion: "Christian",
    caste: "Roman Catholic",
    City: "Vasco",
    State: "Goa",
    country: "India",
    occupation: "Engineer",
    Address: "3838 Lane, Vasco, Goa, India",
  },
  {
    id: 42,
    Age: "25",
    Height: "5'7\"",
    Language: "Hindi",
    Religion: "Muslim",
    caste: "Syed",
    City: "Meerut",
    State: "Uttar Pradesh",
    country: "India",
    occupation: "Teacher",
    Address: "3939 Street, Meerut, Uttar Pradesh, India",
  },
  {
    id: 43,
    Age: "30",
    Height: "5'9\"",
    Language: "Tamil",
    Religion: "Hindu",
    caste: "Brahmin",
    City: "Erode",
    State: "Tamil Nadu",
    country: "India",
    occupation: "Doctor",
    Address: "4040 Avenue, Erode, Tamil Nadu, India",
  },
  {
    id: 44,
    Age: "28",
    Height: "5'8\"",
    Language: "Telugu",
    Religion: "Hindu",
    caste: "Kamma",
    City: "Rajahmundry",
    State: "Andhra Pradesh",
    country: "India",
    occupation: "Scientist",
    Address: "4141 Circle, Rajahmundry, Andhra Pradesh, India",
  },
  {
    id: 45,
    Age: "27",
    Height: "5'7\"",
    Language: "Kannada",
    Religion: "Christian",
    caste: "Gowda",
    City: "Belgaum",
    State: "Karnataka",
    country: "India",
    occupation: "Lawyer",
    Address: "4242 Drive, Belgaum, Karnataka, India",
  },
  {
    id: 46,
    Age: "26",
    Height: "5'6\"",
    Language: "Malayalam",
    Religion: "Hindu",
    caste: "Nair",
    City: "Alappuzha",
    State: "Kerala",
    country: "India",
    occupation: "Engineer",
    Address: "4343 Lane, Alappuzha, Kerala, India",
  },
  {
    id: 47,
    Age: "24",
    Height: "5'9\"",
    Language: "Gujarati",
    Religion: "Jain",
    caste: "Bania",
    City: "Bhavnagar",
    State: "Gujarat",
    country: "India",
    occupation: "Doctor",
    Address: "4444 Street, Bhavnagar, Gujarat, India",
  },
  {
    id: 48,
    Age: "29",
    Height: "5'10\"",
    Language: "Punjabi",
    Religion: "Sikh",
    caste: "Jat",
    City: "Ludhiana",
    State: "Punjab",
    country: "India",
    occupation: "Teacher",
    Address: "4545 Avenue, Ludhiana, Punjab, India",
  },
  {
    id: 49,
    Age: "28",
    Height: "5'7\"",
    Language: "Marathi",
    Religion: "Hindu",
    caste: "Maratha",
    City: "Kolhapur",
    State: "Maharashtra",
    country: "India",
    occupation: "Scientist",
    Address: "4646 Circle, Kolhapur, Maharashtra, India",
  },
  {
    id: 50,
    Age: "26",
    Height: "5'6\"",
    Language: "Bengali",
    Religion: "Hindu",
    caste: "Kayastha",
    City: "Durgapur",
    State: "West Bengal",
    country: "India",
    occupation: "Lawyer",
    Address: "4747 Drive, Durgapur, West Bengal, India",
  },
];

export const RelationShip = [
  "Myself",
  "Daughter",
  "Son",
  "Sister",
  "Brother",
  "Relative",
  "Friend",
];

export const List = [
  {
    Title: "By Gender",
    Subtitle: ["Tamil Brides", "Tamil Grooms"],
  },
  {
    Title: "By Religion",
    Subtitle: ["Hindu Matrimony", "Muslim Matrimony", "Christian Matrimony"],
  },
  {
    Title: "By Caste",
    Subtitle: [
      "Adi Dravida Matrimony",
      "Vanniyar Matrimony",
      "Nadar Matrimony",
      "Devar Matrimony",
      "Agamudayar Matrimony",
      "Vishwakarma Matrimony",
      "Nadar Matrimony",
      "Devar Matrimony",
    ],
  },
  {
    Title: "By City",
    Subtitle: [
      "Chennai Matrimony",
      "Coimbatore Matrimony",
      "Bangalore Matrimony",
      "Madurai Matrimony",
      "Salem Matrimony",
      "Tiruchirappalli Matrimony",
      "Erode Matrimony",
      "Vellore Matrimony",
      "Tiruppur Matrimony",
    ],
  },
  {
    Title: "By State",
    Subtitle: [
      "Tamil Nadu Matrimony",
      "Karnataka Matrimony",
      "Pondicherry Matrimony",
      "Kerala Matrimony",
      "Maharashtra Matrimony",
      "Andhra Pradesh Matrimony",
      "Delhi Matrimony",
      "Andaman & Nicobar Matrimony",
      "Telangana Matrimony",
    ],
  },
  {
    Title: "By Country",
    Subtitle: [
      "NRI Matrimony",
      "Malaysia NRI Matrimony",
      "UAE NRI Matrimony",
      "Singapore NRI Matrimony",
      "USA NRI Matrimony",
      "Sri Lanka NRI Matrimony",
      "Saudi Arabia NRI Matrimony",
      "Kuwait NRI Matrimony",
      "Qatar NRI Matrimony",
    ],
  },
  {
    Title: "By Education",
    Subtitle: [
      "B.E",
      "Diploma",
      "B.Com",
      "B.Tech",
      "MBA",
      "B.Sc",
      "B.A",
      "BCA",
    ],
  },
  {
    Title: "By Profession",
    Subtitle: [
      "Business Owner",
      "Supervisor",
      "Software Professional",
      "Executive",
      "Manager",
      "Officer",
      "Technician",
      "Engineer-Non IT",
      "Teaching",
      "Agriculture",
    ],
  },
];
export const Help = ["24x7 Live help", "Contact us", "Feedback", "FAQs"];

export const OtherService = [
  "EliteMatrimony.com",
  "Jodii",
  "Jodi",
  "Muslim match App Store",
  "Muslim match Play Store",
];

export const WeddingServices = ["Mandap.com", "WeddingBazaar.com"];

export const information = [
  "About Us",
  "Awards",
  "Milestones",
  "Register Free",
  "Partner Search",
  "Member Login",
  "Success stories",
  "Payment Options",
  "Careers",
  "Media Room",
  "TV Commercials",
  "Advertise with us",
  "Terms & Conditions",
  "Privacy Policy",
];

export const MatrimonyServices = [
  "HappyMarriages.com",
  "Matrimonial Sites",
  "Matrimonial Websites",
  "Tamil Matrimony Branches",
  "Tamil Jathagam",
];

export const Regional = [
  "Assamese Matrimony",
  "Bengali Matrimony",
  "Bihari Matrimony",
  "Gujarati Matrimony",
  "Hindi Matrimony",
  " Kannada Matrimony",
  " Kerala Matrimony",
  "Marathi Matrimony",
  "Marwadi Matrimony",
  "Oriya Matrimony",
  "Parsi Matrimony",
  "Punjabi Matrimony",
  "Rajasthani Matrimony",
  "Sindhi Matrimony",
  "Tamil Matrimony",
  "Telugu Matrimony",
  "Urdu Matrimony",
];

export const SliderImg = [Cimage1, Cimage2, Cimage3, Cimage4, Cimage5, Cimage6];
